"""create_all_tables

Revision ID: 2a159cef40c4
Revises: 
Create Date: 2026-03-25 13:09:35.949774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a159cef40c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cgkra_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name,'') || ' ' || coalesce(mission,'') || ' ' || coalesce(vision,''))", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_lower_name', 'companies', [sa.literal_column('lower(name)')], unique=True)
    op.create_index('ix_companies_search_vector', 'companies', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('ix_sessions_last_active_at', 'sessions', ['last_active_at'], unique=False)
    op.create_table('functional_areas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_functional_areas_company_name')
    )
    op.create_index('ix_functional_areas_company_id', 'functional_areas', ['company_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('pdf', 'docx', 'markdown')", name='ck_generated_documents_format'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'ready', 'failed')", name='ck_generated_documents_status'),
    sa.CheckConstraint("type IN ('briefing', 'cgkra-narrative')", name='ck_generated_documents_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['cgkra_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_documents_company_type', 'generated_documents', ['company_id', 'type'], unique=False)
    op.create_index('ix_generated_documents_status', 'generated_documents', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('filename_or_subject', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('who', sa.Text(), nullable=True),
    sa.Column('interaction_date', sa.Text(), nullable=True),
    sa.Column('src', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(filename_or_subject,'') || ' ' || coalesce(raw_content,''))", persisted=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name='ck_sources_status'),
    sa.CheckConstraint("type IN ('email', 'upload')", name='ck_sources_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_company_id', 'sources', ['company_id'], unique=False)
    op.create_index('ix_sources_received_at', 'sources', [sa.literal_column('received_at DESC')], unique=False)
    op.create_index('ix_sources_search_vector', 'sources', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_sources_status', 'sources', ['status'], unique=False)
    op.create_table('inferred_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('functional_area_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('inferred_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('merged_into_entity_type', sa.Text(), nullable=True),
    sa.Column('merged_into_entity_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(inferred_value,'') || ' ' || coalesce(corrected_value,''))", persisted=True), nullable=False),
    sa.CheckConstraint("category IN ('functional-area', 'person', 'relationship', 'technology', 'process', 'cgkra-cs', 'cgkra-gw', 'cgkra-kp', 'cgkra-rm', 'cgkra-aop', 'swot-s', 'swot-w', 'swot-o', 'swot-th', 'action-item', 'other')", name='ck_inferred_facts_category'),
    sa.CheckConstraint("merged_into_entity_type IS NULL OR merged_into_entity_type IN ('person', 'functional_area')", name='ck_inferred_facts_merged_entity_type'),
    sa.CheckConstraint("status != 'corrected' OR corrected_value IS NOT NULL", name='ck_inferred_facts_corrected_requires_value'),
    sa.CheckConstraint("status != 'merged' OR (merged_into_entity_type IS NOT NULL AND merged_into_entity_id IS NOT NULL)", name='ck_inferred_facts_merged_requires_target'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'corrected', 'merged', 'dismissed')", name='ck_inferred_facts_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['functional_area_id'], ['functional_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inferred_facts_category', 'inferred_facts', ['category'], unique=False)
    op.create_index('ix_inferred_facts_company_status', 'inferred_facts', ['company_id', 'status'], unique=False)
    op.create_index('ix_inferred_facts_functional_area_id', 'inferred_facts', ['functional_area_id'], unique=False)
    op.create_index('ix_inferred_facts_search_vector', 'inferred_facts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_inferred_facts_source_id', 'inferred_facts', ['source_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('primary_area_id', sa.UUID(), nullable=True),
    sa.Column('reports_to_person_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name,'') || ' ' || coalesce(title,''))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_area_id'], ['functional_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reports_to_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persons_company_id', 'persons', ['company_id'], unique=False)
    op.create_index('ix_persons_reports_to_person_id', 'persons', ['reports_to_person_id'], unique=False)
    op.create_index('ix_persons_search_vector', 'persons', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('functional_area_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('inferred_fact_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(description,'') || ' ' || coalesce(notes,''))", persisted=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'complete')", name='ck_action_items_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['functional_area_id'], ['functional_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inferred_fact_id'], ['inferred_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_items_company_status', 'action_items', ['company_id', 'status'], unique=False)
    op.create_index('ix_action_items_search_vector', 'action_items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_action_items_status', 'action_items', ['status'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('subordinate_person_id', sa.UUID(), nullable=False),
    sa.Column('manager_person_id', sa.UUID(), nullable=False),
    sa.Column('inferred_fact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inferred_fact_id'], ['inferred_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subordinate_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subordinate_person_id', 'manager_person_id', name='uq_relationships_sub_mgr')
    )
    op.create_index('ix_relationships_company_id', 'relationships', ['company_id'], unique=False)
    op.create_index('ix_relationships_manager_person_id', 'relationships', ['manager_person_id'], unique=False)
    op.create_index('ix_relationships_subordinate_person_id', 'relationships', ['subordinate_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationships_subordinate_person_id', table_name='relationships')
    op.drop_index('ix_relationships_manager_person_id', table_name='relationships')
    op.drop_index('ix_relationships_company_id', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_action_items_status', table_name='action_items')
    op.drop_index('ix_action_items_search_vector', table_name='action_items', postgresql_using='gin')
    op.drop_index('ix_action_items_company_status', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_persons_search_vector', table_name='persons', postgresql_using='gin')
    op.drop_index('ix_persons_reports_to_person_id', table_name='persons')
    op.drop_index('ix_persons_company_id', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_inferred_facts_source_id', table_name='inferred_facts')
    op.drop_index('ix_inferred_facts_search_vector', table_name='inferred_facts', postgresql_using='gin')
    op.drop_index('ix_inferred_facts_functional_area_id', table_name='inferred_facts')
    op.drop_index('ix_inferred_facts_company_status', table_name='inferred_facts')
    op.drop_index('ix_inferred_facts_category', table_name='inferred_facts')
    op.drop_table('inferred_facts')
    op.drop_index('ix_sources_status', table_name='sources')
    op.drop_index('ix_sources_search_vector', table_name='sources', postgresql_using='gin')
    op.drop_index('ix_sources_received_at', table_name='sources')
    op.drop_index('ix_sources_company_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_generated_documents_status', table_name='generated_documents')
    op.drop_index('ix_generated_documents_company_type', table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('ix_functional_areas_company_id', table_name='functional_areas')
    op.drop_table('functional_areas')
    op.drop_index('ix_sessions_last_active_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('credentials')
    op.drop_index('ix_companies_search_vector', table_name='companies', postgresql_using='gin')
    op.drop_index('ix_companies_lower_name', table_name='companies')
    op.drop_table('companies')
    op.drop_table('cgkra_templates')
    # ### end Alembic commands ###
