"""add_llm_context_mode_to_companies

Revision ID: 454cf50473b8
Revises: fcd27cd40ae3
Create Date: 2026-04-09 08:55:25.555397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454cf50473b8'
down_revision: Union[str, None] = 'fcd27cd40ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('llm_context_mode', sa.Text(), server_default=sa.text("'accepted_facts'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'llm_context_mode')
    # ### end Alembic commands ###
