"""add_source_line_to_inferred_facts

Revision ID: fcd27cd40ae3
Revises: 2a159cef40c4
Create Date: 2026-03-31 10:15:57.561003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd27cd40ae3'
down_revision: Union[str, None] = '2a159cef40c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_facts', sa.Column('source_line', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inferred_facts', 'source_line')
    # ### end Alembic commands ###
